<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('municipios')->delete();

        $municipios = [
            ['id' => 1, 'state_id' => 1, 'municipio' => 'Alto Orinoco'],
            ['id' => 2, 'state_id' => 1, 'municipio' => 'Atabapo'],
            ['id' => 3, 'state_id' => 1, 'municipio' => 'Atures'],
            ['id' => 4, 'state_id' => 1, 'municipio' => 'Autana'],
            ['id' => 5, 'state_id' => 1, 'municipio' => 'Manapiare'],
            ['id' => 6, 'state_id' => 1, 'municipio' => 'Maroa'],
            ['id' => 7, 'state_id' => 1, 'municipio' => 'Río Negro'],
            ['id' => 8, 'state_id' => 2, 'municipio' => 'Anaco'],
            ['id' => 9, 'state_id' => 2, 'municipio' => 'Aragua'],
            ['id' => 10, 'state_id' => 2, 'municipio' => 'Manuel Ezequiel Bruzual'],
            ['id' => 11, 'state_id' => 2, 'municipio' => 'Diego Bautista Urbaneja'],
            ['id' => 12, 'state_id' => 2, 'municipio' => 'Fernando Peñalver'],
            ['id' => 13, 'state_id' => 2, 'municipio' => 'Francisco Del Carmen Carvajal'],
            ['id' => 14, 'state_id' => 2, 'municipio' => 'General Sir Arthur McGregor'],
            ['id' => 15, 'state_id' => 2, 'municipio' => 'Guanta'],
            ['id' => 16, 'state_id' => 2, 'municipio' => 'Independencia'],
            ['id' => 17, 'state_id' => 2, 'municipio' => 'José Gregorio Monagas'],
            ['id' => 18, 'state_id' => 2, 'municipio' => 'Juan Antonio Sotillo'],
            ['id' => 19, 'state_id' => 2, 'municipio' => 'Juan Manuel Cajigal'],
            ['id' => 20, 'state_id' => 2, 'municipio' => 'Libertad'],
            ['id' => 21, 'state_id' => 2, 'municipio' => 'Francisco de Miranda'],
            ['id' => 22, 'state_id' => 2, 'municipio' => 'Pedro María Freites'],
            ['id' => 23, 'state_id' => 2, 'municipio' => 'Píritu'],
            ['id' => 24, 'state_id' => 2, 'municipio' => 'San José de Guanipa'],
            ['id' => 25, 'state_id' => 2, 'municipio' => 'San Juan de Capistrano'],
            ['id' => 26, 'state_id' => 2, 'municipio' => 'Santa Ana'],
            ['id' => 27, 'state_id' => 2, 'municipio' => 'Simón Bolívar'],
            ['id' => 28, 'state_id' => 2, 'municipio' => 'Simón Rodríguez'],
            ['id' => 29, 'state_id' => 3, 'municipio' => 'Achaguas'],
            ['id' => 30, 'state_id' => 3, 'municipio' => 'Biruaca'],
            ['id' => 31, 'state_id' => 3, 'municipio' => 'Muñóz'],
            ['id' => 32, 'state_id' => 3, 'municipio' => 'Páez'],
            ['id' => 33, 'state_id' => 3, 'municipio' => 'Pedro Camejo'],
            ['id' => 34, 'state_id' => 3, 'municipio' => 'Rómulo Gallegos'],
            ['id' => 35, 'state_id' => 3, 'municipio' => 'San Fernando'],
            ['id' => 36, 'state_id' => 4, 'municipio' => 'Atanasio Girardot'],
            ['id' => 37, 'state_id' => 4, 'municipio' => 'Bolívar'],
            ['id' => 38, 'state_id' => 4, 'municipio' => 'Camatagua'],
            ['id' => 39, 'state_id' => 4, 'municipio' => 'Francisco Linares Alcántara'],
            ['id' => 40, 'state_id' => 4, 'municipio' => 'José Ángel Lamas'],
            ['id' => 41, 'state_id' => 4, 'municipio' => 'José Félix Ribas'],
            ['id' => 42, 'state_id' => 4, 'municipio' => 'José Rafael Revenga'],
            ['id' => 43, 'state_id' => 4, 'municipio' => 'Libertador'],
            ['id' => 44, 'state_id' => 4, 'municipio' => 'Mario Briceño Iragorry'],
            ['id' => 45, 'state_id' => 4, 'municipio' => 'Ocumare de la Costa de Oro'],
            ['id' => 46, 'state_id' => 4, 'municipio' => 'San Casimiro'],
            ['id' => 47, 'state_id' => 4, 'municipio' => 'San Sebastián'],
            ['id' => 48, 'state_id' => 4, 'municipio' => 'Santiago Mariño'],
            ['id' => 49, 'state_id' => 4, 'municipio' => 'Santos Michelena'],
            ['id' => 50, 'state_id' => 4, 'municipio' => 'Sucre'],
            ['id' => 51, 'state_id' => 4, 'municipio' => 'Tovar'],
            ['id' => 52, 'state_id' => 4, 'municipio' => 'Urdaneta'],
            ['id' => 53, 'state_id' => 4, 'municipio' => 'Zamora'],
            ['id' => 54, 'state_id' => 5, 'municipio' => 'Alberto Arvelo Torrealba'],
            ['id' => 55, 'state_id' => 5, 'municipio' => 'Andrés Eloy Blanco'],
            ['id' => 56, 'state_id' => 5, 'municipio' => 'Antonio José de Sucre'],
            ['id' => 57, 'state_id' => 5, 'municipio' => 'Arismendi'],
            ['id' => 58, 'state_id' => 5, 'municipio' => 'Barinas'],
            ['id' => 59, 'state_id' => 5, 'municipio' => 'Bolívar'],
            ['id' => 60, 'state_id' => 5, 'municipio' => 'Cruz Paredes'],
            ['id' => 61, 'state_id' => 5, 'municipio' => 'Ezequiel Zamora'],
            ['id' => 62, 'state_id' => 5, 'municipio' => 'Obispos'],
            ['id' => 63, 'state_id' => 5, 'municipio' => 'Pedraza'],
            ['id' => 64, 'state_id' => 5, 'municipio' => 'Rojas'],
            ['id' => 65, 'state_id' => 5, 'municipio' => 'Sosa'],
            ['id' => 66, 'state_id' => 6, 'municipio' => 'Caroní'],
            ['id' => 67, 'state_id' => 6, 'municipio' => 'Cedeño'],
            ['id' => 68, 'state_id' => 6, 'municipio' => 'El Callao'],
            ['id' => 69, 'state_id' => 6, 'municipio' => 'Gran Sabana'],
            ['id' => 70, 'state_id' => 6, 'municipio' => 'Heres'],
            ['id' => 71, 'state_id' => 6, 'municipio' => 'Piar'],
            ['id' => 72, 'state_id' => 6, 'municipio' => 'Angostura (Raúl Leoni)'],
            ['id' => 73, 'state_id' => 6, 'municipio' => 'Roscio'],
            ['id' => 74, 'state_id' => 6, 'municipio' => 'Sifontes'],
            ['id' => 75, 'state_id' => 6, 'municipio' => 'Sucre'],
            ['id' => 76, 'state_id' => 6, 'municipio' => 'Padre Pedro Chien'],
            ['id' => 77, 'state_id' => 7, 'municipio' => 'Bejuma'],
            ['id' => 78, 'state_id' => 7, 'municipio' => 'Carlos Arvelo'],
            ['id' => 79, 'state_id' => 7, 'municipio' => 'Diego Ibarra'],
            ['id' => 80, 'state_id' => 7, 'municipio' => 'Guacara'],
            ['id' => 81, 'state_id' => 7, 'municipio' => 'Juan José Mora'],
            ['id' => 82, 'state_id' => 7, 'municipio' => 'Libertador'],
            ['id' => 83, 'state_id' => 7, 'municipio' => 'Los Guayos'],
            ['id' => 84, 'state_id' => 7, 'municipio' => 'Miranda'],
            ['id' => 85, 'state_id' => 7, 'municipio' => 'Montalbán'],
            ['id' => 86, 'state_id' => 7, 'municipio' => 'Naguanagua'],
            ['id' => 87, 'state_id' => 7, 'municipio' => 'Puerto Cabello'],
            ['id' => 88, 'state_id' => 7, 'municipio' => 'San Diego'],
            ['id' => 89, 'state_id' => 7, 'municipio' => 'San Joaquín'],
            ['id' => 90, 'state_id' => 7, 'municipio' => 'Valencia'],
            ['id' => 91, 'state_id' => 8, 'municipio' => 'Anzoátegui'],
            ['id' => 92, 'state_id' => 8, 'municipio' => 'Tinaquillo'],
            ['id' => 93, 'state_id' => 8, 'municipio' => 'Girardot'],
            ['id' => 94, 'state_id' => 8, 'municipio' => 'Lima Blanco'],
            ['id' => 95, 'state_id' => 8, 'municipio' => 'Pao de San Juan Bautista'],
            ['id' => 96, 'state_id' => 8, 'municipio' => 'Ricaurte'],
            ['id' => 97, 'state_id' => 8, 'municipio' => 'Rómulo Gallegos'],
            ['id' => 98, 'state_id' => 8, 'municipio' => 'San Carlos'],
            ['id' => 99, 'state_id' => 8, 'municipio' => 'Tinaco'],
            ['id' => 100, 'state_id' => 9, 'municipio' => 'Antonio Díaz'],
            ['id' => 101, 'state_id' => 9, 'municipio' => 'Casacoima'],
            ['id' => 102, 'state_id' => 9, 'municipio' => 'Pedernales'],
            ['id' => 103, 'state_id' => 9, 'municipio' => 'Tucupita'],
            ['id' => 104, 'state_id' => 10, 'municipio' => 'Acosta'],
            ['id' => 105, 'state_id' => 10, 'municipio' => 'Bolívar'],
            ['id' => 106, 'state_id' => 10, 'municipio' => 'Buchivacoa'],
            ['id' => 107, 'state_id' => 10, 'municipio' => 'Cacique Manaure'],
            ['id' => 108, 'state_id' => 10, 'municipio' => 'Carirubana'],
            ['id' => 109, 'state_id' => 10, 'municipio' => 'Colina'],
            ['id' => 110, 'state_id' => 10, 'municipio' => 'Dabajuro'],
            ['id' => 111, 'state_id' => 10, 'municipio' => 'Democracia'],
            ['id' => 112, 'state_id' => 10, 'municipio' => 'Falcón'],
            ['id' => 113, 'state_id' => 10, 'municipio' => 'Federación'],
            ['id' => 114, 'state_id' => 10, 'municipio' => 'Jacura'],
            ['id' => 115, 'state_id' => 10, 'municipio' => 'José Laurencio Silva'],
            ['id' => 116, 'state_id' => 10, 'municipio' => 'Los Taques'],
            ['id' => 117, 'state_id' => 10, 'municipio' => 'Mauroa'],
            ['id' => 118, 'state_id' => 10, 'municipio' => 'Miranda'],
            ['id' => 119, 'state_id' => 10, 'municipio' => 'Monseñor Iturriza'],
            ['id' => 120, 'state_id' => 10, 'municipio' => 'Palmasola'],
            ['id' => 121, 'state_id' => 10, 'municipio' => 'Petit'],
            ['id' => 122, 'state_id' => 10, 'municipio' => 'Píritu'],
            ['id' => 123, 'state_id' => 10, 'municipio' => 'San Francisco'],
            ['id' => 124, 'state_id' => 10, 'municipio' => 'Sucre'],
            ['id' => 125, 'state_id' => 10, 'municipio' => 'Tocópero'],
            ['id' => 126, 'state_id' => 10, 'municipio' => 'Unión'],
            ['id' => 127, 'state_id' => 10, 'municipio' => 'Urumaco'],
            ['id' => 128, 'state_id' => 10, 'municipio' => 'Zamora'],
            ['id' => 129, 'state_id' => 11, 'municipio' => 'Camaguán'],
            ['id' => 130, 'state_id' => 11, 'municipio' => 'Chaguaramas'],
            ['id' => 131, 'state_id' => 11, 'municipio' => 'El Socorro'],
            ['id' => 132, 'state_id' => 11, 'municipio' => 'José Félix Ribas'],
            ['id' => 133, 'state_id' => 11, 'municipio' => 'José Tadeo Monagas'],
            ['id' => 134, 'state_id' => 11, 'municipio' => 'Juan Germán Roscio'],
            ['id' => 135, 'state_id' => 11, 'municipio' => 'Julián Mellado'],
            ['id' => 136, 'state_id' => 11, 'municipio' => 'Las Mercedes'],
            ['id' => 137, 'state_id' => 11, 'municipio' => 'Leonardo Infante'],
            ['id' => 138, 'state_id' => 11, 'municipio' => 'Pedro Zaraza'],
            ['id' => 139, 'state_id' => 11, 'municipio' => 'Ortíz'],
            ['id' => 140, 'state_id' => 11, 'municipio' => 'San Gerónimo de Guayabal'],
            ['id' => 141, 'state_id' => 11, 'municipio' => 'San José de Guaribe'],
            ['id' => 142, 'state_id' => 11, 'municipio' => 'Santa María de Ipire'],
            ['id' => 143, 'state_id' => 11, 'municipio' => 'Sebastián Francisco de Miranda'],
            ['id' => 144, 'state_id' => 12, 'municipio' => 'Andrés Eloy Blanco'],
            ['id' => 145, 'state_id' => 12, 'municipio' => 'Crespo'],
            ['id' => 146, 'state_id' => 12, 'municipio' => 'Iribarren'],
            ['id' => 147, 'state_id' => 12, 'municipio' => 'Jiménez'],
            ['id' => 148, 'state_id' => 12, 'municipio' => 'Morán'],
            ['id' => 149, 'state_id' => 12, 'municipio' => 'Palavecino'],
            ['id' => 150, 'state_id' => 12, 'municipio' => 'Simón Planas'],
            ['id' => 151, 'state_id' => 12, 'municipio' => 'Torres'],
            ['id' => 152, 'state_id' => 12, 'municipio' => 'Urdaneta'],
            ['id' => 179, 'state_id' => 13, 'municipio' => 'Alberto Adriani'],
            ['id' => 180, 'state_id' => 13, 'municipio' => 'Andrés Bello'],
            ['id' => 181, 'state_id' => 13, 'municipio' => 'Antonio Pinto Salinas'],
            ['id' => 182, 'state_id' => 13, 'municipio' => 'Aricagua'],
            ['id' => 183, 'state_id' => 13, 'municipio' => 'Arzobispo Chacón'],
            ['id' => 184, 'state_id' => 13, 'municipio' => 'Campo Elías'],
            ['id' => 185, 'state_id' => 13, 'municipio' => 'Caracciolo Parra Olmedo'],
            ['id' => 186, 'state_id' => 13, 'municipio' => 'Cardenal Quintero'],
            ['id' => 187, 'state_id' => 13, 'municipio' => 'Guaraque'],
            ['id' => 188, 'state_id' => 13, 'municipio' => 'Julio César Salas'],
            ['id' => 189, 'state_id' => 13, 'municipio' => 'Justo Briceño'],
            ['id' => 190, 'state_id' => 13, 'municipio' => 'Libertador'],
            ['id' => 191, 'state_id' => 13, 'municipio' => 'Miranda'],
            ['id' => 192, 'state_id' => 13, 'municipio' => 'Obispo Ramos de Lora'],
            ['id' => 193, 'state_id' => 13, 'municipio' => 'Padre Noguera'],
            ['id' => 194, 'state_id' => 13, 'municipio' => 'Pueblo Llano'],
            ['id' => 195, 'state_id' => 13, 'municipio' => 'Rangel'],
            ['id' => 196, 'state_id' => 13, 'municipio' => 'Rivas Dávila'],
            ['id' => 197, 'state_id' => 13, 'municipio' => 'Santos Marquina'],
            ['id' => 198, 'state_id' => 13, 'municipio' => 'Sucre'],
            ['id' => 199, 'state_id' => 13, 'municipio' => 'Tovar'],
            ['id' => 200, 'state_id' => 13, 'municipio' => 'Tulio Febres Cordero'],
            ['id' => 201, 'state_id' => 13, 'municipio' => 'Zea'],
            ['id' => 223, 'state_id' => 14, 'municipio' => 'Acevedo'],
            ['id' => 224, 'state_id' => 14, 'municipio' => 'Andrés Bello'],
            ['id' => 225, 'state_id' => 14, 'municipio' => 'Baruta'],
            ['id' => 226, 'state_id' => 14, 'municipio' => 'Brión'],
            ['id' => 227, 'state_id' => 14, 'municipio' => 'Buroz'],
            ['id' => 228, 'state_id' => 14, 'municipio' => 'Carrizal'],
            ['id' => 229, 'state_id' => 14, 'municipio' => 'Chacao'],
            ['id' => 230, 'state_id' => 14, 'municipio' => 'Cristóbal Rojas'],
            ['id' => 231, 'state_id' => 14, 'municipio' => 'El Hatillo'],
            ['id' => 232, 'state_id' => 14, 'municipio' => 'Guaicaipuro'],
            ['id' => 233, 'state_id' => 14, 'municipio' => 'Independencia'],
            ['id' => 234, 'state_id' => 14, 'municipio' => 'Lander'],
            ['id' => 235, 'state_id' => 14, 'municipio' => 'Los Salias'],
            ['id' => 236, 'state_id' => 14, 'municipio' => 'Páez'],
            ['id' => 237, 'state_id' => 14, 'municipio' => 'Paz Castillo'],
            ['id' => 238, 'state_id' => 14, 'municipio' => 'Pedro Gual'],
            ['id' => 239, 'state_id' => 14, 'municipio' => 'Plaza'],
            ['id' => 240, 'state_id' => 14, 'municipio' => 'Simón Bolívar'],
            ['id' => 241, 'state_id' => 14, 'municipio' => 'Sucre'],
            ['id' => 242, 'state_id' => 14, 'municipio' => 'Urdaneta'],
            ['id' => 243, 'state_id' => 14, 'municipio' => 'Zamora'],
            ['id' => 258, 'state_id' => 15, 'municipio' => 'Acosta'],
            ['id' => 259, 'state_id' => 15, 'municipio' => 'Aguasay'],
            ['id' => 260, 'state_id' => 15, 'municipio' => 'Bolívar'],
            ['id' => 261, 'state_id' => 15, 'municipio' => 'Caripe'],
            ['id' => 262, 'state_id' => 15, 'municipio' => 'Cedeño'],
            ['id' => 263, 'state_id' => 15, 'municipio' => 'Ezequiel Zamora'],
            ['id' => 264, 'state_id' => 15, 'municipio' => 'Libertador'],
            ['id' => 265, 'state_id' => 15, 'municipio' => 'Maturín'],
            ['id' => 266, 'state_id' => 15, 'municipio' => 'Piar'],
            ['id' => 267, 'state_id' => 15, 'municipio' => 'Punceres'],
            ['id' => 268, 'state_id' => 15, 'municipio' => 'Santa Bárbara'],
            ['id' => 269, 'state_id' => 15, 'municipio' => 'Sotillo'],
            ['id' => 270, 'state_id' => 15, 'municipio' => 'Uracoa'],
            ['id' => 271, 'state_id' => 16, 'municipio' => 'Antolín del Campo'],
            ['id' => 272, 'state_id' => 16, 'municipio' => 'Arismendi'],
            ['id' => 273, 'state_id' => 16, 'municipio' => 'García'],
            ['id' => 274, 'state_id' => 16, 'municipio' => 'Gómez'],
            ['id' => 275, 'state_id' => 16, 'municipio' => 'Maneiro'],
            ['id' => 276, 'state_id' => 16, 'municipio' => 'Marcano'],
            ['id' => 277, 'state_id' => 16, 'municipio' => 'Mariño'],
            ['id' => 278, 'state_id' => 16, 'municipio' => 'Península de Macanao'],
            ['id' => 279, 'state_id' => 16, 'municipio' => 'Tubores'],
            ['id' => 280, 'state_id' => 16, 'municipio' => 'Villalba'],
            ['id' => 281, 'state_id' => 16, 'municipio' => 'Díaz'],
            ['id' => 282, 'state_id' => 17, 'municipio' => 'Agua Blanca'],
            ['id' => 283, 'state_id' => 17, 'municipio' => 'Araure'],
            ['id' => 284, 'state_id' => 17, 'municipio' => 'Esteller'],
            ['id' => 285, 'state_id' => 17, 'municipio' => 'Guanare'],
            ['id' => 286, 'state_id' => 17, 'municipio' => 'Guanarito'],
            ['id' => 287, 'state_id' => 17, 'municipio' => 'Monseñor José Vicente de Unda'],
            ['id' => 288, 'state_id' => 17, 'municipio' => 'Ospino'],
            ['id' => 289, 'state_id' => 17, 'municipio' => 'Páez'],
            ['id' => 290, 'state_id' => 17, 'municipio' => 'Papelón'],
            ['id' => 291, 'state_id' => 17, 'municipio' => 'San Genaro de Boconoíto'],
            ['id' => 292, 'state_id' => 17, 'municipio' => 'San Rafael de Onoto'],
            ['id' => 293, 'state_id' => 17, 'municipio' => 'Santa Rosalía'],
            ['id' => 294, 'state_id' => 17, 'municipio' => 'Sucre'],
            ['id' => 295, 'state_id' => 17, 'municipio' => 'Turén'],
            ['id' => 296, 'state_id' => 18, 'municipio' => 'Andrés Eloy Blanco'],
            ['id' => 297, 'state_id' => 18, 'municipio' => 'Andrés Mata'],
            ['id' => 298, 'state_id' => 18, 'municipio' => 'Arismendi'],
            ['id' => 299, 'state_id' => 18, 'municipio' => 'Benítez'],
            ['id' => 300, 'state_id' => 18, 'municipio' => 'Bermúdez'],
            ['id' => 301, 'state_id' => 18, 'municipio' => 'Bolívar'],
            ['id' => 302, 'state_id' => 18, 'municipio' => 'Cajigal'],
            ['id' => 303, 'state_id' => 18, 'municipio' => 'Cruz Salmerón Acosta'],
            ['id' => 304, 'state_id' => 18, 'municipio' => 'Libertador'],
            ['id' => 305, 'state_id' => 18, 'municipio' => 'Mariño'],
            ['id' => 306, 'state_id' => 18, 'municipio' => 'Mejía'],
            ['id' => 307, 'state_id' => 18, 'municipio' => 'Montes'],
            ['id' => 308, 'state_id' => 18, 'municipio' => 'Ribero'],
            ['id' => 309, 'state_id' => 18, 'municipio' => 'Sucre'],
            ['id' => 310, 'state_id' => 18, 'municipio' => 'Valdéz'],
            ['id' => 341, 'state_id' => 19, 'municipio' => 'Andrés Bello'],
            ['id' => 342, 'state_id' => 19, 'municipio' => 'Antonio Rómulo Costa'],
            ['id' => 343, 'state_id' => 19, 'municipio' => 'Ayacucho'],
            ['id' => 344, 'state_id' => 19, 'municipio' => 'Bolívar'],
            ['id' => 345, 'state_id' => 19, 'municipio' => 'Cárdenas'],
            ['id' => 346, 'state_id' => 19, 'municipio' => 'Córdoba'],
            ['id' => 347, 'state_id' => 19, 'municipio' => 'Fernández Feo'],
            ['id' => 348, 'state_id' => 19, 'municipio' => 'Francisco de Miranda'],
            ['id' => 349, 'state_id' => 19, 'municipio' => 'García de Hevia'],
            ['id' => 350, 'state_id' => 19, 'municipio' => 'Guásimos'],
            ['id' => 351, 'state_id' => 19, 'municipio' => 'Independencia'],
            ['id' => 352, 'state_id' => 19, 'municipio' => 'Jáuregui'],
            ['id' => 353, 'state_id' => 19, 'municipio' => 'José María Vargas'],
            ['id' => 354, 'state_id' => 19, 'municipio' => 'Junín'],
            ['id' => 355, 'state_id' => 19, 'municipio' => 'Libertad'],
            ['id' => 356, 'state_id' => 19, 'municipio' => 'Libertador'],
            ['id' => 357, 'state_id' => 19, 'municipio' => 'Lobatera'],
            ['id' => 358, 'state_id' => 19, 'municipio' => 'Michelena'],
            ['id' => 359, 'state_id' => 19, 'municipio' => 'Panamericano'],
            ['id' => 360, 'state_id' => 19, 'municipio' => 'Pedro María Ureña'],
            ['id' => 361, 'state_id' => 19, 'municipio' => 'Rafael Urdaneta'],
            ['id' => 362, 'state_id' => 19, 'municipio' => 'Samuel Darío Maldonado'],
            ['id' => 363, 'state_id' => 19, 'municipio' => 'San Cristóbal'],
            ['id' => 364, 'state_id' => 19, 'municipio' => 'Seboruco'],
            ['id' => 365, 'state_id' => 19, 'municipio' => 'Simón Rodríguez'],
            ['id' => 366, 'state_id' => 19, 'municipio' => 'Sucre'],
            ['id' => 367, 'state_id' => 19, 'municipio' => 'Torbes'],
            ['id' => 368, 'state_id' => 19, 'municipio' => 'Uribante'],
            ['id' => 369, 'state_id' => 19, 'municipio' => 'San Judas Tadeo'],
            ['id' => 370, 'state_id' => 20, 'municipio' => 'Andrés Bello'],
            ['id' => 371, 'state_id' => 20, 'municipio' => 'Boconó'],
            ['id' => 372, 'state_id' => 20, 'municipio' => 'Bolívar'],
            ['id' => 373, 'state_id' => 20, 'municipio' => 'Candelaria'],
            ['id' => 374, 'state_id' => 20, 'municipio' => 'Carache'],
            ['id' => 375, 'state_id' => 20, 'municipio' => 'Escuque'],
            ['id' => 376, 'state_id' => 20, 'municipio' => 'José Felipe Márquez Cañizalez'],
            ['id' => 377, 'state_id' => 20, 'municipio' => 'Juan Vicente Campos Elías'],
            ['id' => 378, 'state_id' => 20, 'municipio' => 'La Ceiba'],
            ['id' => 379, 'state_id' => 20, 'municipio' => 'Miranda'],
            ['id' => 380, 'state_id' => 20, 'municipio' => 'Monte Carmelo'],
            ['id' => 381, 'state_id' => 20, 'municipio' => 'Motatán'],
            ['id' => 382, 'state_id' => 20, 'municipio' => 'Pampán'],
            ['id' => 383, 'state_id' => 20, 'municipio' => 'Pampanito'],
            ['id' => 384, 'state_id' => 20, 'municipio' => 'Rafael Rangel'],
            ['id' => 385, 'state_id' => 20, 'municipio' => 'San Rafael de Carvajal'],
            ['id' => 386, 'state_id' => 20, 'municipio' => 'Sucre'],
            ['id' => 387, 'state_id' => 20, 'municipio' => 'Trujillo'],
            ['id' => 388, 'state_id' => 20, 'municipio' => 'Urdaneta'],
            ['id' => 389, 'state_id' => 20, 'municipio' => 'Valera'],
            ['id' => 390, 'state_id' => 21, 'municipio' => 'Vargas'],
            ['id' => 391, 'state_id' => 22, 'municipio' => 'Arístides Bastidas'],
            ['id' => 392, 'state_id' => 22, 'municipio' => 'Bolívar'],
            ['id' => 407, 'state_id' => 22, 'municipio' => 'Bruzual'],
            ['id' => 408, 'state_id' => 22, 'municipio' => 'Cocorote'],
            ['id' => 409, 'state_id' => 22, 'municipio' => 'Independencia'],
            ['id' => 410, 'state_id' => 22, 'municipio' => 'José Antonio Páez'],
            ['id' => 411, 'state_id' => 22, 'municipio' => 'La Trinidad'],
            ['id' => 412, 'state_id' => 22, 'municipio' => 'Manuel Monge'],
            ['id' => 413, 'state_id' => 22, 'municipio' => 'Nirgua'],
            ['id' => 414, 'state_id' => 22, 'municipio' => 'Peña'],
            ['id' => 415, 'state_id' => 22, 'municipio' => 'San Felipe'],
            ['id' => 416, 'state_id' => 22, 'municipio' => 'Sucre'],
            ['id' => 417, 'state_id' => 22, 'municipio' => 'Urachiche'],
            ['id' => 418, 'state_id' => 22, 'municipio' => 'José Joaquín Veroes'],
            ['id' => 441, 'state_id' => 23, 'municipio' => 'Almirante Padilla'],
            ['id' => 442, 'state_id' => 23, 'municipio' => 'Baralt'],
            ['id' => 443, 'state_id' => 23, 'municipio' => 'Cabimas'],
            ['id' => 444, 'state_id' => 23, 'municipio' => 'Catatumbo'],
            ['id' => 445, 'state_id' => 23, 'municipio' => 'Colón'],
            ['id' => 446, 'state_id' => 23, 'municipio' => 'Francisco Javier Pulgar'],
            ['id' => 447, 'state_id' => 23, 'municipio' => 'Páez'],
            ['id' => 448, 'state_id' => 23, 'municipio' => 'Jesús Enrique Losada'],
            ['id' => 449, 'state_id' => 23, 'municipio' => 'Jesús María Semprún'],
            ['id' => 450, 'state_id' => 23, 'municipio' => 'La Cañada de Urdaneta'],
            ['id' => 451, 'state_id' => 23, 'municipio' => 'Lagunillas'],
            ['id' => 452, 'state_id' => 23, 'municipio' => 'Machiques de Perijá'],
            ['id' => 453, 'state_id' => 23, 'municipio' => 'Mara'],
            ['id' => 454, 'state_id' => 23, 'municipio' => 'Maracaibo'],
            ['id' => 455, 'state_id' => 23, 'municipio' => 'Miranda'],
            ['id' => 456, 'state_id' => 23, 'municipio' => 'Rosario de Perijá'],
            ['id' => 457, 'state_id' => 23, 'municipio' => 'San Francisco'],
            ['id' => 458, 'state_id' => 23, 'municipio' => 'Santa Rita'],
            ['id' => 459, 'state_id' => 23, 'municipio' => 'Simón Bolívar'],
            ['id' => 460, 'state_id' => 23, 'municipio' => 'Sucre'],
            ['id' => 461, 'state_id' => 23, 'municipio' => 'Valmore Rodríguez'],
            ['id' => 462, 'state_id' => 24, 'municipio' => 'Libertador'],
        ];

        foreach (array_chunk($municipios, 100) as $chunk) {
            DB::table('municipios')->insert($chunk);
        }
    }
}